AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logger-with-cache

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        LOG_LEVEL: INFO
        MemorySize: 512
Resources:
  GetUserDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/getUserDetails/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserTable
      Events:
        Sample:
          Type: Api
          Properties:
            Path: /user
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref UserTable

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Type: Number
        Name: userId

Outputs:
  Api:
    Description: 'API Gateway endpoint URL for Prod stage for getUserDetails function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sampleApi/'
  UserTableName:
    Description: 'User table name'
    Value: !Ref UserTable
  GetUserDetailsFunction:
    Description: 'Get User Details Lambda Function ARN'
    Value: !GetAtt GetUserDetailsFunction.Arn
  GetUserDetailsFunctionIamRole:
    Description: 'Implicit IAM Role created for get user details function'
    Value: !GetAtt GetUserDetailsFunctionRole.Arn
